/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 interactive_cards_by_ahmadi.gltf -t 
*/

import { OrthographicCamera, useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { Suspense } from "react";
import * as THREE from "three";
// to install
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0_instance_0: THREE.Mesh;
    mesh_1_instance_0: THREE.Mesh;
    mesh_2_instance_0: THREE.Mesh;
    mesh_0_instance_1: THREE.Mesh;
    mesh_1_instance_1: THREE.Mesh;
    mesh_2_instance_1: THREE.Mesh;
    mesh_0_instance_2: THREE.Mesh;
    mesh_1_instance_2: THREE.Mesh;
    mesh_2_instance_2: THREE.Mesh;
    mesh_0_instance_3: THREE.Mesh;
    mesh_1_instance_3: THREE.Mesh;
    mesh_2_instance_3: THREE.Mesh;
    mesh_0_instance_4: THREE.Mesh;
    mesh_1_instance_4: THREE.Mesh;
    mesh_2_instance_4: THREE.Mesh;
    mesh_0_instance_5: THREE.Mesh;
    mesh_1_instance_5: THREE.Mesh;
    mesh_2_instance_5: THREE.Mesh;
    mesh_0_instance_6: THREE.Mesh;
    mesh_1_instance_6: THREE.Mesh;
    mesh_2_instance_6: THREE.Mesh;
    mesh_0_instance_7: THREE.Mesh;
    mesh_1_instance_7: THREE.Mesh;
    mesh_2_instance_7: THREE.Mesh;
    mesh_0_instance_8: THREE.Mesh;
    mesh_1_instance_8: THREE.Mesh;
    mesh_2_instance_8: THREE.Mesh;
    mesh_0_instance_9: THREE.Mesh;
    mesh_1_instance_9: THREE.Mesh;
    mesh_2_instance_9: THREE.Mesh;
    mesh_0_instance_10: THREE.Mesh;
    mesh_1_instance_10: THREE.Mesh;
    mesh_2_instance_10: THREE.Mesh;
    mesh_0_instance_11: THREE.Mesh;
    mesh_1_instance_11: THREE.Mesh;
    mesh_2_instance_11: THREE.Mesh;
  };
  materials: {};
};

function Card(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/canvas/interactive_cards_by_ahmadi.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-102.946, -74.536, 137.538]} rotation={[0, 0, 1.844]}>
          <directionalLight
            intensity={5.032}
            color="#70dacc"
            rotation={[1.897, -0.181, -1.51]}
          />
          <directionalLight
            intensity={5.032}
            color="#da7070"
            rotation={[-2.698, 0.657, -0.661]}
          />
          <directionalLight
            intensity={1.906}
            color="#7ab6e7"
            rotation={[-0.645, 0.463, 1.035]}
          />
        </group>
        <group
          position={[-19.492, 33.816, 11.132]}
          rotation={[-0.619, -0.011, 0.315]}
        >
          <group position={[0, 227, 0]} rotation={[0.436, 0.157, 0.576]}>
            <mesh
              geometry={nodes.mesh_0_instance_0.geometry}
              material={nodes.mesh_0_instance_0.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_0.geometry}
              material={nodes.mesh_1_instance_0.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_0.geometry}
              material={nodes.mesh_2_instance_0.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[14.517, 226.535, 0]}
            rotation={[0.436, 0.157, 0.512]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_1.geometry}
              material={nodes.mesh_0_instance_1.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_1.geometry}
              material={nodes.mesh_1_instance_1.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_1.geometry}
              material={nodes.mesh_2_instance_1.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[28.975, 225.143, 0]}
            rotation={[0.436, 0.157, 0.448]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_2.geometry}
              material={nodes.mesh_0_instance_2.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_2.geometry}
              material={nodes.mesh_1_instance_2.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_2.geometry}
              material={nodes.mesh_2_instance_2.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[43.314, 222.829, 0]}
            rotation={[0.436, 0.157, 0.384]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_3.geometry}
              material={nodes.mesh_0_instance_3.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_3.geometry}
              material={nodes.mesh_1_instance_3.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_3.geometry}
              material={nodes.mesh_2_instance_3.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[57.475, 219.603, 0]}
            rotation={[0.436, 0.157, 0.32]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_4.geometry}
              material={nodes.mesh_0_instance_4.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_4.geometry}
              material={nodes.mesh_1_instance_4.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_4.geometry}
              material={nodes.mesh_2_instance_4.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[71.402, 215.478, 0]}
            rotation={[0.436, 0.157, 0.256]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_5.geometry}
              material={nodes.mesh_0_instance_5.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_5.geometry}
              material={nodes.mesh_1_instance_5.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_5.geometry}
              material={nodes.mesh_2_instance_5.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[85.036, 210.471, 0]}
            rotation={[0.436, 0.157, 0.192]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_6.geometry}
              material={nodes.mesh_0_instance_6.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_6.geometry}
              material={nodes.mesh_1_instance_6.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_6.geometry}
              material={nodes.mesh_2_instance_6.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[98.322, 204.602, 0]}
            rotation={[0.436, 0.157, 0.128]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_7.geometry}
              material={nodes.mesh_0_instance_7.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_7.geometry}
              material={nodes.mesh_1_instance_7.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_7.geometry}
              material={nodes.mesh_2_instance_7.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[111.205, 197.895, 0]}
            rotation={[0.436, 0.157, 0.064]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_8.geometry}
              material={nodes.mesh_0_instance_8.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_8.geometry}
              material={nodes.mesh_1_instance_8.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_8.geometry}
              material={nodes.mesh_2_instance_8.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group position={[123.633, 190.378, 0]} rotation={[0.436, 0.157, 0]}>
            <mesh
              geometry={nodes.mesh_0_instance_9.geometry}
              material={nodes.mesh_0_instance_9.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_9.geometry}
              material={nodes.mesh_1_instance_9.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_9.geometry}
              material={nodes.mesh_2_instance_9.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[135.555, 182.082, 0]}
            rotation={[0.436, 0.157, -0.064]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_10.geometry}
              material={nodes.mesh_0_instance_10.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_10.geometry}
              material={nodes.mesh_1_instance_10.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_10.geometry}
              material={nodes.mesh_2_instance_10.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
          <group
            position={[146.922, 173.04, 0]}
            rotation={[0.436, 0.157, -0.128]}
          >
            <mesh
              geometry={nodes.mesh_0_instance_11.geometry}
              material={nodes.mesh_0_instance_11.material}
              position={[-20.437, -100.599, -1.528]}
            />
            <mesh
              geometry={nodes.mesh_1_instance_11.geometry}
              material={nodes.mesh_1_instance_11.material}
              position={[0, 0, -3.188]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.mesh_2_instance_11.geometry}
              material={nodes.mesh_2_instance_11.material}
              position={[0.904, 90.397, -1.089]}
            />
          </group>
        </group>
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[-18.161, 189.788, 1034.434]}
        />
      </group>
    </group>
  );
}

const CardCanvas = ({ ...props }) => {
  return (
    <Canvas
      style={{
        maxWidth: 500,
        minWidth: 300,
      }}
    >
      <Suspense fallback={null}>
        <Card {...props} />
      </Suspense>
    </Canvas>
  );
};

useGLTF.preload("/canvas/interactive_cards_by_ahmadi.gltf");

export default CardCanvas;
