// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'

// Create Virtual Routes

const LayoutIndexLazyImport = createFileRoute('/_layout/')()
const LayoutCustomizeLazyImport = createFileRoute('/_layout/customize')()
const LayoutContactLazyImport = createFileRoute('/_layout/contact')()
const LayoutCheckoutLazyImport = createFileRoute('/_layout/checkout')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route))

const LayoutCustomizeLazyRoute = LayoutCustomizeLazyImport.update({
  path: '/customize',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/customize.lazy').then((d) => d.Route),
)

const LayoutContactLazyRoute = LayoutContactLazyImport.update({
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/contact.lazy').then((d) => d.Route),
)

const LayoutCheckoutLazyRoute = LayoutCheckoutLazyImport.update({
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/checkout.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/checkout': {
      preLoaderRoute: typeof LayoutCheckoutLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/contact': {
      preLoaderRoute: typeof LayoutContactLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/customize': {
      preLoaderRoute: typeof LayoutCustomizeLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexLazyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutCheckoutLazyRoute,
    LayoutContactLazyRoute,
    LayoutCustomizeLazyRoute,
    LayoutIndexLazyRoute,
  ]),
])
